# Generated by Django 4.2 on 2023-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='name',
            field=models.CharField(choices=[('Aaranshi', 'Aaranshi'), ('LAtika', 'Latika'), ('Shivin', 'Shivin'), ('Keshav', 'Keshav'), ('Geetanjali', 'Geetanjali'), ('Kiara', 'Kiara'), ('Aarav', 'Aarav'), ('Vian', 'Vian'), ('Shamita', 'Shamita')], max_length=100),
        ),
    ]
